name: Update Blobs Data

on:
  schedule:
    # Runs at 1 AM UTC daily
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-blobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run index-all script
        run: pnpm tsx src/scripts/index-all.ts
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}

      - name: Run write-dates script
        run: pnpm tsx src/scripts/write-dates.ts

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/api/blobs/data/
          git add src/api/blobs/dates.json
          git commit -m "chore: update blobs data [skip ci]" || exit 0
          git push 